# can't use mem_limit in a 3.x docker-compose file in non swarm mode
# see https://github.com/docker/compose/issues/4513
version: "2.4"

services:
  traefik:
    image: "traefik:v2.7"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=change@domain.name"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  badoogle-search:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`change.host.name`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      - "traefik.http.services.badoogle-search.loadbalancer.server.port=5000"
    image: ${BADOOGLE_IMAGE:-sherkitty/badoogle-search}
    container_name: badoogle-search
    restart: unless-stopped
    pids_limit: 50
    mem_limit: 256mb
    memswap_limit: 256mb
    # user debian-tor from tor package
    user: badoogle
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - /config/:size=10M,uid=927,gid=927,mode=1700
      - /var/lib/tor/:size=15M,uid=927,gid=927,mode=1700
      - /run/tor/:size=1M,uid=927,gid=927,mode=1700
    environment: # Uncomment to configure environment variables
      # Basic auth configuration, uncomment to enable
      #- BADOOGLE_USER=<auth username>
      #- BADOOGLE_PASS=<auth password>
      # Proxy configuration, uncomment to enable
      #- BADOOGLE_PROXY_USER=<proxy username>
      #- BADOOGLE_PROXY_PASS=<proxy password>
      #- BADOOGLE_PROXY_TYPE=<proxy type (http|https|socks4|socks5)
      #- BADOOGLE_PROXY_LOC=<proxy host/ip>
      # Site alternative configurations, uncomment to enable
      # Note: If not set, the feature will still be available
      # with default values.
      #- BADOOGLE_ALT_TW=farside.link/nitter
      #- BADOOGLE_ALT_YT=farside.link/invidious
      #- BADOOGLE_ALT_IG=farside.link/bibliogram/u
      #- BADOOGLE_ALT_RD=farside.link/libreddit
      #- BADOOGLE_ALT_MD=farside.link/scribe
      #- BADOOGLE_ALT_TL=farside.link/lingva
      #- BADOOGLE_ALT_IMG=farside.link/rimgo
      #- BADOOGLE_ALT_WIKI=farside.link/wikiless
      #- BADOOGLE_ALT_IMDB=farside.link/libremdb
      #- BADOOGLE_ALT_QUORA=farside.link/quetre
      # - BADOOGLE_CONFIG_DISABLE=1
      # - BADOOGLE_CONFIG_SEARCH_LANGUAGE=lang_en
      # - BADOOGLE_CONFIG_GET_ONLY=1
      # - BADOOGLE_CONFIG_COUNTRY=FR
      # - BADOOGLE_CONFIG_PREFERENCES_ENCRYPTED=1
      # - BADOOGLE_CONFIG_PREFERENCES_KEY="NEEDS_TO_BE_MODIFIED"
    #env_file: # Alternatively, load variables from badoogle.env
      #- badoogle.env
    ports:
      - 8000:5000
