# can't use mem_limit in a 3.x docker-compose file in non swarm mode
# see https://github.com/docker/compose/issues/4513
version: "2.4"

services:
  badoogle-search:
    image: ${BADOOGLE_IMAGE:-sherkitty/badoogle-search}
    container_name: badoogle-search
    restart: unless-stopped
    pids_limit: 50
    mem_limit: 256mb
    memswap_limit: 256mb
    # user debian-tor from tor package
    user: badoogle
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - /config/:size=10M,uid=927,gid=927,mode=1700
      - /var/lib/tor/:size=15M,uid=927,gid=927,mode=1700
      - /run/tor/:size=1M,uid=927,gid=927,mode=1700
    #environment: # Uncomment to configure environment variables
      # Basic auth configuration, uncomment to enable
      #- BADOOGLE_USER=<auth username>
      #- BADOOGLE_PASS=<auth password>
      # Proxy configuration, uncomment to enable
      #- BADOOGLE_PROXY_USER=<proxy username>
      #- BADOOGLE_PROXY_PASS=<proxy password>
      #- BADOOGLE_PROXY_TYPE=<proxy type (http|https|socks4|socks5)
      #- BADOOGLE_PROXY_LOC=<proxy host/ip>
      # Site alternative configurations, uncomment to enable
      # Note: If not set, the feature will still be available
      # with default values.
      #- BADOOGLE_ALT_TW=farside.link/nitter
      #- BADOOGLE_ALT_YT=farside.link/invidious
      #- BADOOGLE_ALT_IG=farside.link/bibliogram/u
      #- BADOOGLE_ALT_RD=farside.link/libreddit
      #- BADOOGLE_ALT_MD=farside.link/scribe
      #- BADOOGLE_ALT_TL=farside.link/lingva
      #- BADOOGLE_ALT_IMG=farside.link/rimgo
      #- BADOOGLE_ALT_WIKI=farside.link/wikiless
      #- BADOOGLE_ALT_IMDB=farside.link/libremdb
      #- BADOOGLE_ALT_QUORA=farside.link/quetre
    #env_file: # Alternatively, load variables from badoogle.env
      #- badoogle.env
    ports:
      - 5000:5000
