name: docker_main

on:
  workflow_run:
    workflows: ["tests"]
    branches: [main]
    types:
      - completed

# TODO: Needs refactoring to use reusable workflows and share w/ docker_tests
jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: build and test (docker)
      run: |
        docker build --tag badoogle-search:test .
        docker run --publish 5000:5000 --detach --name badoogle-search-nocompose badoogle-search:test
        sleep 15
        docker exec badoogle-search-nocompose curl -f http://localhost:5000/healthz || exit 1
    - name: build and test (docker-compose)
      run: |
        docker rm -f badoogle-search-nocompose
        BADOOGLE_IMAGE="badoogle-search:test" docker-compose up --detach
        sleep 15
        docker exec badoogle-search curl -f http://localhost:5000/healthz || exit 1
